const MUSIC_DNA_SCHEMA_VERSION = "1.3";

const MUSIC_DNA_DB = {
  schemaVersion: MUSIC_DNA_SCHEMA_VERSION,
  generatedAt: "2026-08-26",
  dailyModel: { tracksPerDay: 3, daysPerWeek: 7, maxTracksPerWeek: 21, missedTracksCreateBacklog: false },
  tracks: {
    "2026-W35-01": {identity:{artist:"Crown Lands",title:"Right Way Back",releaseDate:"2021-03-11",releaseYear:2021,albumOrRelease:"Context: Fearless Pt. I",country:"Canada",locality:"Oshawa, Ontario"},spotify:{id:null,uri:null,resolvedExact:false},discoverDNA:{week:"2026-W35",day:1,dailySlot:1,offered:true,dnaRoute:["Rush","Prog/Hardrock","Crown Lands"],role:"anker"},taxonomy:{allMusicGenres:["Pop/Rock"],allMusicStyles:["Hard Rock","Album Rock","Prog-Rock","American Trad Rock"],taxonomyScope:"ARTIST"},editorial:{whyForYou:"Een sterke verbinding met je Rush-DNA: moderne prog/hardrock met een directe historische band naar Neil Peart en meerdere Rush-producers.",storyTitle:"Een eerbetoon dat ineens heel dichtbij kwam",storySummary:"Right Way Back verscheen op 11 maart 2021. Crown Lands schreef het nummer als eerbetoon aan Neil Peart en aan het idee om verder te gaan waar muzikale helden ophouden.",listenHooks:[{id:"cl-listen-01",title:"De drums als hoofdrolspeler",text:"Luister niet alleen naar het ritme. De drums reageren voortdurend op de riffs en geven het nummer daardoor die nerveuze, progressieve drive.",evidenceType:"EDITORIAL_OBSERVATION",sourceIds:["src-cl-allmusic","src-cl-umc-right-way-back"]}],surpriseHooks:[{id:"cl-surprise-01",hookType:"instrument",label:"Dat wist ik niet!",title:"Neil Pearts drumkit",text:"Tijdens de Nashville-sessies bracht producer Nick Raskulinecz een drumkit tevoorschijn die Neil Peart voor Rush' Snakes & Arrows had gebruikt; Cody Bowles speelde erop.",evidenceType:"SOURCE_FACT",sourceIds:["src-cl-umc-right-way-back"]},{id:"cl-surprise-02",hookType:"producer_connection",label:"De verbinding",title:"Drie lijnen naar Rush",text:"Crown Lands werkte rond deze muziek met drie producers uit de Rush-geschiedenis: Terry Brown, Nick Raskulinecz en David Bottrill.",evidenceType:"SOURCE_FACT",sourceIds:["src-cl-umc-right-way-back"]}]},sourceIds:["src-cl-allmusic","src-cl-umc-right-way-back"]},
    "2026-W35-02": {identity:{artist:"Hällas",title:"Fading Hero",releaseDate:"2020-02-14",releaseYear:2020,albumOrRelease:"Conundrum",country:"Zweden",locality:"Jönköping"},spotify:{id:null,uri:null,resolvedExact:false},discoverDNA:{week:"2026-W35",day:1,dailySlot:2,offered:true,dnaRoute:["70s Prog/Hardrock","Adventure Rock","Hällas"],role:"ontdekking"},taxonomy:{allMusicGenres:["Pop/Rock"],allMusicStyles:["Hard Rock","Progressive Metal","Stoner Metal","Heavy Metal"],taxonomyScope:"ARTIST",artistSelfDescription:"Adventure Rock"},editorial:{whyForYou:"Een moderne Zweedse band die bewust voortbouwt op jaren-70 hardrock en prog, maar daar een eigen fantasy- en avonturenwereld omheen bouwt.",storyTitle:"De held verdwijnt langzaam uit beeld",storySummary:"Fading Hero is het slotnummer van Conundrum, de afsluiting van Hällas' vroege trilogie.",listenHooks:[{id:"ha-listen-01",title:"Een vergeten jaren-80-fantasyfilm?",text:"Luister naar het eerste deel alsof het de soundtrack van een vergeten jaren-80-fantasyfilm is.",evidenceType:"SOURCE_CONTEXT",sourceIds:["src-ha-decibel"]}],surpriseHooks:[{id:"ha-surprise-01",hookType:"genre_story",label:"Dat wist ik niet!",title:"Adventure Rock",text:"Hällas noemt zijn eigen stijl 'Adventure Rock': de band wil dat luisteren voelt alsof je op avontuur of op een queeste bent.",evidenceType:"SOURCE_FACT",sourceIds:["src-ha-decibel"]}]},sourceIds:["src-ha-allmusic","src-ha-bandcamp-fading-hero","src-ha-bandcamp-conundrum","src-ha-decibel","src-ha-deadrhetoric"]},
    "2026-W35-03": {identity:{artist:"The Night Flight Orchestra",title:"Give Us the Moon",releaseDate:"2025-01-31",releaseYear:2025,albumOrRelease:"Give Us the Moon",country:"Zweden",locality:"Helsingborg"},spotify:{id:null,uri:null,resolvedExact:false},discoverDNA:{week:"2026-W35",day:1,dailySlot:3,offered:true,dnaRoute:["Hardrock","AOR","The Night Flight Orchestra"],role:"melodische brug"},taxonomy:{allMusicGenres:["Pop/Rock"],allMusicStyles:["Arena Rock","Hard Rock","Pop-Metal","Heavy Metal"],taxonomyScope:"ARTIST"},editorial:{whyForYou:"Een melodische brug van hardrock naar filmische AOR: groot refrein, jaren-80-glans en toch geworteld in een veel zwaardere rock- en metalwereld.",storyTitle:"Metal-muzikanten die hun andere platenkast openzetten",storySummary:"The Night Flight Orchestra ontstond rond Björn Strid en David Andersson van Soilwork en groeide uit tot een uitgesproken AOR/classic-rockband. Give Us the Moon verscheen in 2025.",listenHooks:[{id:"tnfo-listen-01",title:"Luister naar de contrasten",text:"De zang en hooks zijn glanzend en melodieus, maar onder die AOR-laag hoor je hoe strak en krachtig muzikanten uit een zwaardere metalachtergrond spelen.",evidenceType:"EDITORIAL_OBSERVATION",sourceIds:["src-tnfo-allmusic"]}],surpriseHooks:[{id:"tnfo-surprise-01",hookType:"tour_connection",label:"Op hetzelfde podium",title:"Voorprogramma van KISS",text:"The Night Flight Orchestra opende voor KISS tijdens de laatste twee Zweedse KISS-shows in Dalhalla.",evidenceType:"SOURCE_FACT",sourceIds:["src-tnfo-napalm"]}]},sourceIds:["src-tnfo-allmusic","src-tnfo-napalm"]}
  },
  sources:{
    "src-cl-allmusic":{title:"Crown Lands — Biography",publisher:"AllMusic",url:"https://www.allmusic.com/artist/crown-lands-mn0003910795"},"src-cl-umc-right-way-back":{title:"Crown Lands unleash Context: Fearless Pt. 1 and Right Way Back",publisher:"Universal Music Canada",url:"https://www.universalmusic.ca/press-releases/juno-nominated-crown-lands-unleash-two-new-tracks-context-fearless-pt-1-and-right-way-back/"},"src-ha-allmusic":{title:"Hällas — Biography",publisher:"AllMusic",url:"https://www.allmusic.com/artist/h%C3%A4llas-mn0003452445"},"src-ha-bandcamp-fading-hero":{title:"Fading Hero",publisher:"Hällas / Bandcamp",url:"https://haellas.bandcamp.com/track/fading-hero"},"src-ha-bandcamp-conundrum":{title:"Conundrum",publisher:"Hällas / Bandcamp",url:"https://haellas.bandcamp.com/album/conundrum"},"src-ha-decibel":{title:"Q&A: Kasper Eriksson (Hällas) Finds Himself In A Conundrum",publisher:"Decibel Magazine",url:"https://www.decibelmagazine.com/2020/02/24/kasper-eriksson-hallas-adventure-rock/"},"src-ha-deadrhetoric":{title:"Hällas — Wisdom of the Past",publisher:"Dead Rhetoric",url:"https://deadrhetoric.com/features/hallas-wisdom-of-the-past/"},"src-tnfo-allmusic":{title:"The Night Flight Orchestra — Biography",publisher:"AllMusic",url:"https://www.allmusic.com/artist/the-night-flight-orchestra-mn0002928334"},"src-tnfo-napalm":{title:"The Night Flight Orchestra",publisher:"Napalm Records",url:"https://label.napalmrecords.com/the-night-flight-orchestra"}
  }
};