const MUSIC_DNA_SCHEMA_VERSION = "1.3";

const MUSIC_DNA_DB = {
  schemaVersion: MUSIC_DNA_SCHEMA_VERSION,
  generatedAt: "2026-08-27",
  dailyModel: { tracksPerDay: 3, daysPerWeek: 7, maxTracksPerWeek: 21, missedTracksCreateBacklog: false },
  tracks: {
    "2026-W35-01": {identity:{artist:"Crown Lands",title:"Right Way Back",releaseDate:"2021-03-11",releaseYear:2021,albumOrRelease:"Context: Fearless Pt. I",country:"Canada",locality:"Oshawa, Ontario"},spotify:{id:null,uri:null,resolvedExact:false},discoverDNA:{week:"2026-W35",day:1,dailySlot:1,offered:true,dnaRoute:["Rush","Prog/Hardrock","Crown Lands"],role:"anker"},taxonomy:{allMusicGenres:["Pop/Rock"],allMusicStyles:["Hard Rock","Album Rock","Prog-Rock","American Trad Rock"],taxonomyScope:"ARTIST"},editorial:{whyForYou:"Een sterke verbinding met je Rush-DNA: moderne prog/hardrock met een directe historische band naar Neil Peart en meerdere Rush-producers.",storyTitle:"Een eerbetoon dat ineens heel dichtbij kwam",storySummary:"Right Way Back verscheen op 11 maart 2021. Crown Lands schreef het nummer als eerbetoon aan Neil Peart en aan het idee om verder te gaan waar muzikale helden ophouden.",listenHooks:[{id:"cl-listen-01",title:"De drums als hoofdrolspeler",text:"Luister niet alleen naar het ritme. De drums reageren voortdurend op de riffs en geven het nummer daardoor die nerveuze, progressieve drive.",evidenceType:"EDITORIAL_OBSERVATION",sourceIds:["src-cl-allmusic","src-cl-umc-right-way-back"]}],surpriseHooks:[{id:"cl-surprise-01",hookType:"instrument",label:"Dat wist ik niet!",title:"Neil Pearts drumkit",text:"Tijdens de Nashville-sessies bracht producer Nick Raskulinecz een drumkit tevoorschijn die Neil Peart voor Rush' Snakes & Arrows had gebruikt; Cody Bowles speelde erop.",evidenceType:"SOURCE_FACT",sourceIds:["src-cl-umc-right-way-back"]},{id:"cl-surprise-02",hookType:"producer_connection",label:"De verbinding",title:"Drie lijnen naar Rush",text:"Crown Lands werkte rond deze muziek met drie producers uit de Rush-geschiedenis: Terry Brown, Nick Raskulinecz en David Bottrill.",evidenceType:"SOURCE_FACT",sourceIds:["src-cl-umc-right-way-back"]}]},sourceIds:["src-cl-allmusic","src-cl-umc-right-way-back"]},
    "2026-W35-02": {identity:{artist:"Hällas",title:"Fading Hero",releaseDate:"2020-02-14",releaseYear:2020,albumOrRelease:"Conundrum",country:"Zweden",locality:"Jönköping"},spotify:{id:null,uri:null,resolvedExact:false},discoverDNA:{week:"2026-W35",day:1,dailySlot:2,offered:true,dnaRoute:["70s Prog/Hardrock","Adventure Rock","Hällas"],role:"ontdekking"},taxonomy:{allMusicGenres:["Pop/Rock"],allMusicStyles:["Hard Rock","Progressive Metal","Stoner Metal","Heavy Metal"],taxonomyScope:"ARTIST",artistSelfDescription:"Adventure Rock"},editorial:{whyForYou:"Een moderne Zweedse band die bewust voortbouwt op jaren-70 hardrock en prog, maar daar een eigen fantasy- en avonturenwereld omheen bouwt.",storyTitle:"De held verdwijnt langzaam uit beeld",storySummary:"Fading Hero is het slotnummer van Conundrum, de afsluiting van Hällas' vroege trilogie.",listenHooks:[{id:"ha-listen-01",title:"Een vergeten jaren-80-fantasyfilm?",text:"Luister naar het eerste deel alsof het de soundtrack van een vergeten jaren-80-fantasyfilm is.",evidenceType:"SOURCE_CONTEXT",sourceIds:["src-ha-decibel"]}],surpriseHooks:[{id:"ha-surprise-01",hookType:"genre_story",label:"Dat wist ik niet!",title:"Adventure Rock",text:"Hällas noemt zijn eigen stijl 'Adventure Rock': de band wil dat luisteren voelt alsof je op avontuur of op een queeste bent.",evidenceType:"SOURCE_FACT",sourceIds:["src-ha-decibel"]}]},sourceIds:["src-ha-allmusic","src-ha-bandcamp-fading-hero","src-ha-bandcamp-conundrum","src-ha-decibel","src-ha-deadrhetoric"]},
    "2026-W35-03": {identity:{artist:"The Night Flight Orchestra",title:"Give Us the Moon",releaseDate:"2025-01-31",releaseYear:2025,albumOrRelease:"Give Us the Moon",country:"Zweden",locality:"Helsingborg"},spotify:{id:null,uri:null,resolvedExact:false},discoverDNA:{week:"2026-W35",day:1,dailySlot:3,offered:true,dnaRoute:["Hardrock","AOR","The Night Flight Orchestra"],role:"melodische brug"},taxonomy:{allMusicGenres:["Pop/Rock"],allMusicStyles:["Arena Rock","Hard Rock","Pop-Metal","Heavy Metal"],taxonomyScope:"ARTIST"},editorial:{whyForYou:"Een melodische brug van hardrock naar filmische AOR: groot refrein, jaren-80-glans en toch geworteld in een veel zwaardere rock- en metalwereld.",storyTitle:"Metal-muzikanten die hun andere platenkast openzetten",storySummary:"The Night Flight Orchestra ontstond rond Björn Strid en David Andersson van Soilwork en groeide uit tot een uitgesproken AOR/classic-rockband. Give Us the Moon verscheen in 2025.",listenHooks:[{id:"tnfo-listen-01",title:"Luister naar de contrasten",text:"De zang en hooks zijn glanzend en melodieus, maar onder die AOR-laag hoor je hoe strak en krachtig muzikanten uit een zwaardere metalachtergrond spelen.",evidenceType:"EDITORIAL_OBSERVATION",sourceIds:["src-tnfo-allmusic"]}],surpriseHooks:[{id:"tnfo-surprise-01",hookType:"tour_connection",label:"Op hetzelfde podium",title:"Voorprogramma van KISS",text:"The Night Flight Orchestra opende voor KISS tijdens de laatste twee Zweedse KISS-shows in Dalhalla.",evidenceType:"SOURCE_FACT",sourceIds:["src-tnfo-napalm"]}]},sourceIds:["src-tnfo-allmusic","src-tnfo-napalm"]},

    "2026-W35-04": {identity:{artist:"Dirty Honey",title:"When I'm Gone",releaseDate:null,releaseYear:2019,albumOrRelease:"Dirty Honey",country:"United States",locality:null},spotify:{id:null,uri:null,resolvedExact:false},discoverDNA:{week:"2026-W35",day:2,dailySlot:1,offered:false,dnaRoute:["70s hardrock","Dirty Honey"],role:"anker"},taxonomy:{allMusicGenres:["Pop/Rock"],allMusicStyles:["Hard Rock","American Trad Rock","Album Rock"],taxonomyScope:"ARTIST"},editorial:{whyForYou:"Een relatief veilige brug vanuit klassieke hardrock naar een jongere band.",storyTitle:"De riff wees de weg",storySummary:"When I'm Gone hielp Dirty Honey beseffen dat hun natuurlijke terrein bluesgebaseerde klassieke hardrock was.",listenHooks:[{id:"dh-listen-01",title:"Losse hardrockgroove",text:"Luister naar de riffgerichte, losse hardrockgroove en de bluesbasis onder het refrein.",evidenceType:"SOURCE_CONTEXT",sourceIds:["src-dh-allmusic"]}],surpriseHooks:[{id:"dh-surprise-01",hookType:"tour_connection",label:"Dat wist ik niet!",title:"Van doorbraak naar grote podia",text:"Na de doorbraak volgden tournees met onder andere KISS, Guns N' Roses en The Black Crowes.",evidenceType:"SOURCE_FACT",sourceIds:["src-dh-allmusic"]}]},sourceIds:["src-dh-allmusic"]},
    "2026-W35-05": {identity:{artist:"The Struts",title:"Pretty Vicious",releaseDate:"2023-11-03",releaseYear:2023,albumOrRelease:"Pretty Vicious",country:"United Kingdom",locality:null},spotify:{id:null,uri:null,resolvedExact:false},discoverDNA:{week:"2026-W35",day:2,dailySlot:2,offered:false,dnaRoute:["Sweet","Slade","neo-glam","The Struts"],role:"anker"},taxonomy:{allMusicGenres:["Pop/Rock"],allMusicStyles:["American Trad Rock","Neo-Glam","Hard Rock","Alternative/Indie Rock"],taxonomyScope:"ARTIST"},editorial:{whyForYou:"Directe moderne aansluiting op Sweet/Slade en glam/hardrock.",storyTitle:"Britse glam, maar dan nu",storySummary:"The Struts bouwen moderne glam/hardrock op een duidelijke Britse glamtraditie.",listenHooks:[{id:"ts-listen-01",title:"Theater en drive",text:"Luister naar de combinatie van theatrale zang, groot refrein en glamrockdrive.",evidenceType:"SOURCE_CONTEXT",sourceIds:["src-struts-allmusic"]}],surpriseHooks:[{id:"ts-surprise-01",hookType:"influence_connection",label:"De verbinding",title:"Sweet en Slade",text:"AllMusic trekt expliciet de lijn naar Slade en Sweet; de band opende ook voor Foo Fighters en Slash.",evidenceType:"SOURCE_FACT",sourceIds:["src-struts-allmusic"]}]},sourceIds:["src-struts-allmusic"]},
    "2026-W35-06": {identity:{artist:"The Warning",title:"S!CK",releaseDate:null,releaseYear:2024,albumOrRelease:"Keep Me Fed",country:"Mexico",locality:"Monterrey"},spotify:{id:null,uri:null,resolvedExact:false},discoverDNA:{week:"2026-W35",day:2,dailySlot:3,offered:false,dnaRoute:["modern hardrock","The Warning"],role:"moderne hardrock"},taxonomy:{allMusicGenres:["Pop/Rock"],allMusicStyles:["Hard Rock","Heavy Metal"],releaseAllMusicGenres:["Pop/Rock"],releaseAllMusicStyles:["Alternative Metal","Hard Rock","Heavy Metal","Alternative/Indie Rock"],taxonomyScope:"ARTIST_AND_RELEASE"},editorial:{whyForYou:"Een jongere, modernere hardrock/heavy-metaltest.",storyTitle:"Van covers naar de grote podia",storySummary:"De drie zussen uit Monterrey groeiden van online rockcovers door naar grote internationale podia.",listenHooks:[{id:"tw-listen-01",title:"Compact en modern",text:"Luister naar de compacte moderne productie en hoe het refrein hardrock en alternative metal bij elkaar brengt.",evidenceType:"SOURCE_CONTEXT",sourceIds:["src-warning-allmusic"]}],surpriseHooks:[{id:"tw-surprise-01",hookType:"tour_connection",label:"Dat wist ik niet!",title:"Van Metallica-cover naar wereldpodia",text:"Na hun vroege Metallica-, AC/DC- en Guns N' Roses-covers speelden ze later voor Def Leppard, Muse en Guns N' Roses.",evidenceType:"SOURCE_FACT",sourceIds:["src-warning-allmusic"]}]},sourceIds:["src-warning-allmusic"]}
  },
  sources:{
    "src-cl-allmusic":{title:"Crown Lands — Biography",publisher:"AllMusic",url:"https://www.allmusic.com/artist/crown-lands-mn0003910795"},
    "src-cl-umc-right-way-back":{title:"Crown Lands unleash Context: Fearless Pt. 1 and Right Way Back",publisher:"Universal Music Canada",url:"https://www.universalmusic.ca/press-releases/juno-nominated-crown-lands-unleash-two-new-tracks-context-fearless-pt-1-and-right-way-back/"},
    "src-ha-allmusic":{title:"Hällas — Biography",publisher:"AllMusic",url:"https://www.allmusic.com/artist/h%C3%A4llas-mn0003452445"},
    "src-ha-bandcamp-fading-hero":{title:"Fading Hero",publisher:"Hällas / Bandcamp",url:"https://haellas.bandcamp.com/track/fading-hero"},
    "src-ha-bandcamp-conundrum":{title:"Conundrum",publisher:"Hällas / Bandcamp",url:"https://haellas.bandcamp.com/album/conundrum"},
    "src-ha-decibel":{title:"Q&A: Kasper Eriksson (Hällas) Finds Himself In A Conundrum",publisher:"Decibel Magazine",url:"https://www.decibelmagazine.com/2020/02/24/kasper-eriksson-hallas-adventure-rock/"},
    "src-ha-deadrhetoric":{title:"Hällas — Wisdom of the Past",publisher:"Dead Rhetoric",url:"https://deadrhetoric.com/features/hallas-wisdom-of-the-past/"},
    "src-tnfo-allmusic":{title:"The Night Flight Orchestra — Biography",publisher:"AllMusic",url:"https://www.allmusic.com/artist/the-night-flight-orchestra-mn0002928334"},
    "src-tnfo-napalm":{title:"The Night Flight Orchestra",publisher:"Napalm Records",url:"https://label.napalmrecords.com/the-night-flight-orchestra"},
    "src-dh-allmusic":{title:"Dirty Honey biography / taxonomy",publisher:"AllMusic",url:"https://www.allmusic.com/artist/dirty-honey-mn0003836081"},
    "src-struts-allmusic":{title:"The Struts biography / Pretty Vicious",publisher:"AllMusic",url:"https://www.allmusic.com/artist/the-struts-mn0003131865"},
    "src-warning-allmusic":{title:"The Warning biography / Keep Me Fed",publisher:"AllMusic",url:"https://www.allmusic.com/artist/the-warning-mn0003614847"}
  }
};